### ISSUE TITLE
Symfony 5 Compatibility

### ISSUE THREAD

**Issue by protracks** [anyx/LoginGateBundle#20]
Just wondering when S5 compatibility is to be expected :)

**Comment by protracks** [comment]
Is the project abandoned?

**Comment by protracks** [comment]
Well, for anyone wondering, we stopped using anyx/LoginGateBundle. We built our own brute force protection.

Anyx, Thank you for building this. It worked wonders for S4. <3

**Comment by anyx** [comment]
@protracks thanks. Unfortunately I'm not using this bundle for my own projects right now and don't have much time for upgrading this. Maybe someday)

**Comment by anyx** [comment]
The Someday became!
https://github.com/anyx/LoginGateBundle/releases/tag/1.0.0
