### ISSUE TITLE
Use username instead of IP

### ISSUE THREAD

**Issue by antoine1003** [anyx/LoginGateBundle#25]
Hi,
I use your bundle to secure the login page but I encounter an issue : users use a VPN and have the same IP when using the login page. So if one user is blocked every other user is blocked when he try to login after. Is there any wait to check the number of attempts using the username instead of IP?

Thanks !

**Comment by anyx** [comment]
Hi, @antoine1003 
Yes, right now we are aren't saving username in attempts storage. I agree - using combination of username and ip looks like a good idea, but now I don't have match time for work with this bundle.

So maybe later I will add this feature, or you can send PR)

**Comment by antoine1003** [comment]
Hey,
Thanks for this quick answer ! Okay Ino problem, I'll try to make a PR but I have not really used to symfony bundle. But i'll try :)

**Comment by antoine1003** [comment]
Okay, I tried but I have no idea how to make it clean...

**Comment by anyx** [comment]
So fast)
I'll try to find time for it

**Comment by antoine1003** [comment]
Cool thanks 🎉

**Comment by anyx** [comment]
@antoine1003 just released version `2.0.0-beta` with storing usernames in database.
Please, look to updated documentation (there is a important part about usernames) and try to use it.

If everything fine, I'll publish major release

**Comment by antoine1003** [comment]
@anyx Wow, you're fast :D Thanks a lot, let me try it, I let you know

**Comment by antoine1003** [comment]
@anyx I tested the version `2.0.0-beta` with the following resolver : 
```php
<?php
namespace App\Service;

use Anyx\LoginGateBundle\Service\UsernameResolverInterface;
use Symfony\Component\HttpFoundation\Request;

/**
 * Username resolver for json login
 */
class UsernameResolver implements UsernameResolverInterface
{
    public function resolve(Request $request)
    {
        $requestData = $request->request->get('_username');

        return $requestData ? $requestData: null;
    }
}
```
And after some tests everything is working fine ! 👍

**Comment by anyx** [comment]
@antoine1003 cool, just released `2.0.0` version

**Comment by antoine1003** [comment]
@anyx Soo cool thank you for your reactivity! 🙂

**Comment by anyx** [comment]
@antoine1003 you are welcome!
