### ISSUE TITLE
Symfony v6 compatibility

### ISSUE THREAD

**Issue by victormacko** [anyx/LoginGateBundle#36]
Are you looking to add compatibility with Symfony v6 (released in November, 2021) by chance, or is there something else which we should use instead if not?

Great bundle btw, i've been using it for quite a while!

**Comment by victormacko** [comment]
Ah no worries @anyx , let us know if you think you'll have time, otherwise if not i'll try giving it a go and put in a PR if I have some success.

**Comment by skelly-2-1** [comment]
Also very interested in this, unfortunately can't really contribute because my knowledge of PHP is quite limited.

**Comment by anyx** [comment]
I started to do this. I hope, I will finish this until weekend

**Comment by anyx** [comment]
Just released version `3.0.0` with Symfony 6 support. 
Please, check this out.

P. S.: current version of Symfony has [login throttling](https://symfony.com/doc/current/security#limiting-login-attempts) feature out of the box, so there is not so many cases left when this bundle can be useful)

Peace for everyone!

**Comment by victormacko** [comment]
Ace, thank you for your help!
