### ISSUE TITLE
Symfony 7 support

### ISSUE THREAD

**Issue by victormacko** [anyx/LoginGateBundle#40]
Symfony 7 just got released (yay!) the other day - would it be possible to have this package also updated accordingly so SF7 can be used with this component?
Not sure if it's just the composer.json file or something else as well would be needed.

Thanks so much for creating such a great component.

**Comment by anyx** [comment]
hi @victormacko. Just released  version 4.0.0 with support Symfony 7. Since https://packagist.org/packages/doctrine/mongodb-odm-bundle is not supports Symfony 7, right now this bundle supports only orm.

Please, test it

**Comment by victormacko** [comment]
@anyx Seems to work well -- i'm waiting on a few other packages as well so can't fully upgrade just yet unfortunately.
Can I suggest also using "^7.0" vs "7.0.*" when referring to the symfony version (the later would mean only very minor updates can go through, vs 7.1 or 7.2, etc when the time comes in a few months time).

Thank you for your work & support of the package -- it's really appreciated!

**Comment by victormacko** [comment]
@anyx Happy New Year!
I've run into the same issue which was reported here; https://github.com/anyx/LoginGateBundle/issues/41 where the php type is set to string, but the doctrine type is int, which leads to the doctrine validation to fail.

**Comment by anyx** [comment]
@victormacko Happy New Year you too!
Just released version 4.0.2 with fixed property type, supporting mongodb and changed dependencies.

Take a look, please

**Comment by victormacko** [comment]
Looks perfect @anyx , thank you for the super fast release!
