### ISSUE TITLE
Wrong property type in Entity

### ISSUE THREAD

**Issue by TheCodingHood** [anyx/LoginGateBundle#41]
Run:
bin/console doctrine:schema:validate --skip-sync

Result:
[FAIL] The entity-class Anyx\LoginGateBundle\Entity\FailureLoginAttempt mapping is invalid:
 * The field 'Anyx\LoginGateBundle\Entity\FailureLoginAttempt#id' has the property type 'string' that differs from the metadata field type 'int' returned by the 'integer' DBAL type.

**Comment by anyx** [comment]
@TheCodingHood  thanks for a report

fixed here
