### ISSUE TITLE
composer.json: require php >=8.2, even for no-dev

### ISSUE THREAD

**Issue by kouinkouin** [anyx/LoginGateBundle#43]
Hello,

First, thanks for this project.

Today, I can `composer require anyx/login-gate-bundle` even if I am running on a PHP 7.4, because the `package.json` allow it.
Of course, that fails when PHP does not understand `private` in a `__construct()`.

Can you move the `php: >=8.2` from `require-dev` to `require`?
If not, why that could not be possible?

Thanks,

**Comment by anyx** [comment]
Hello @kouinkouin 

You are welcome!))
Honestly, I don't think that my bundle should used now in prior that similar functionality already implemented in symfony security bundle https://symfony.com/doc/current/security.html#limiting-login-attempts. Have you tried this? Or it not supported in php 7.4?
